### ISSUE TITLE
Wrong size fractions

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-bpns-crate#29]
The size_frac_low and size_frac_up should be the other way round (in the water_sampling.csv). 
When size_frac is 3-200 then size_frac_low should be 3 and size_frac_up should be 200. 
Also,  size_frac is 0.2-3 then size_frac_low should be 0.2 and size_frac_up should be 3. 
Now it's the other way round. 

@melinalou

**Comment by melinalou** [comment]
done

**Comment by cpavloud** [comment]
Please confirm that this is also changed in the google spreadsheets.

**Comment by melinalou** [comment]
confirmed
