### ISSUE TITLE
EMO BON in contactPoint

### ISSUE THREAD

**Issue by laurianvm** [emo-bon/observatory-bpns-crate#43]
In [/observatory-bpns-crate/extra-metadata.json](https://github.com/emo-bon/observatory-bpns-crate/blob/main/extra-metadata.json)
```
{
...
    "dcat:contactPoint":[
                ...
                {"@type": "vcard:Contact", "email": "emobon@embrc.eu"}
            ],
}
...
{
            "@id":"_:EMOBON",
            "@type":"Organization",
            "name":"EMO BON",
            "url":"https://www.embrc.eu/emo-bon"
}
```
schema.org allows to define a Project (~ type of Organization)
In context of using local references (~ro-crate spec recommendation), would therefore suggest:
```
{
...
    "dcat:contactPoint":[
                ...
                {"@id":"_:EMOBON",}
            ],
}
...
{
            "@id":"_:EMOBON",
            "@type":"Project",
            "name":"EMO BON",
            "email": "emobon@embrc.eu",
            "url":"https://www.embrc.eu/emo-bon"
}
```

However, do both entities represent the same? 
i.e. is emobon@embrc.eu the email of the Organization with name "EMO BON" and url "https://www.embrc.eu/emo-bon"?

**Comment by kmexter** [comment]
yes, that email address and url is for emobon. 
and addiitonally, emobon is a member of embrc and I think it is important to say that

**Comment by laurianvm** [comment]
okay, can we make a distinction likewise?
```
{
            "@id":"_:EMOBON",
            "@type":"Project",
            "name":"EMO BON",
            "email": "emobon@embrc.eu",
            "parentOrganization": {"@id": "_:EMBRC"},
            "url":"https://www.embrc.eu/emo-bon"
}, 
{
            "@id":"_:EMBRC",
            "@type":"Organization",
            "name":"EMBRC",
            "email": "xxx",
            "url":"https://www.embrc.eu/"
},
```

**Comment by kmexter** [comment]
this is correct. embrc's email address is secretariat@embrc.eu and it has an edmo: https://edmo.seadatanet.org/report/5669 and a ror https://ror.org/0038zss60
