### ISSUE TITLE
semantics of provider

### ISSUE THREAD

**Issue by laurianvm** [emo-bon/observatory-bpns-crate#44]
In [extra-metadata.json](https://github.com/emo-bon/observatory-bpns-crate/blob/main/extra-metadata.json#L46)
```
{
...
    "provider":[
                {"@id":"_:VLIZ"},
                {"@id":"_:UGENT"},
                {"@id":"_:RBINS"},
                {"@id":"_:KUL"},
                {"@id":"_:KlaasD"}
            ],
}
```

Instead of 'provider', would semantics of 'creator' also fit the person/organization mentioned here, in the context of this dataset?

Reason I'm asking, [FE DCAT-AP](https://github.com/fair-ease/asset-standards/blob/main/DCAT-AP/FE-DCAT-AP-class-diagram.drawio.png) has dct:creator (but doesn't mention provider) and I think it would be useful to minimize possible confusion between: 
- extra-metadata.json 
- FE-DCATAP-metadata.json (which is to represent metadata conforming to FE DCAT AP)

suggesting to change to:
extra-metadata.json 
```
    "creator":[
                {"@id":"_:VLIZ"},
                {"@id":"_:UGENT"},
                {"@id":"_:RBINS"},
                {"@id":"_:KUL"},
                {"@id":"_:KlaasD"}
            ],
}
```
FE-DCATAP-metadata.json
```
    "dct:creator":[
                {"@id":"_:VLIZ"},
                {"@id":"_:UGENT"},
                {"@id":"_:RBINS"},
                {"@id":"_:KUL"},
                {"@id":"_:KlaasD"}
            ],
}
```

**Comment by kmexter** [comment]
that depends on what FE want creator to be saying
These people are not the creator of the metadata record or the dataset, they are the providers of the data in the dataset. what do FE expect "creator" to mean? 
so, what are the agents and their roles in the FE dcat template - we can then decide how that maps to our agents and roles

**Comment by laurianvm** [comment]
FE DCAT AP is following the definition as mentioned on the [website](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/creator):
"An entity responsible for making the resource." with the resource being the dataset (not the metadata record about the dataset)

**Comment by kmexter** [comment]
well, no, they are not the creator of the dataset, they are the collectors of the data
the creator is emobon
is there not a term FE is using for "contributors" ?

**Comment by kmexter** [comment]
if not to my question above, then ok: we will have emobon and these people as the creator, and vliz also as we ought to be acknowledged (as the data managers). make everyone a creator as we all contributed to the creation

**Comment by laurianvm** [comment]
This issue depends on the cardinality constraints in the FE DCAT AP:
- if creator is mandatory: we need to define who fits best 'creator' for this dataset, which can be all/any of the people listed as 'provider' in extra-metadata.json atm
- if creator is not mandatory: we can simply extend the FE DCAT AP and use another term in FE-DCAT-AP-metadata.json that better fits the semantics -- (given your explanation, either provider or contributor)

Which makes it dependent on cardinality constraints of the FE DCAT AP, which still need to be defined (see: https://github.com/fair-ease/asset-standards/issues/2) 

Sidenote; If the semantics of 'creator' do not fit the people listed with 'provider' in extra-metadata.json, we do not necessarily need to alter 'provider' to 'creator' in that file 
--> this would mean we're making our own interpretation of 'creator' in context of this dataset
--> better solution in FE DCAT AP metadata description is needed (hence cardinality remark)

**Comment by kmexter** [comment]
I suggest you and I spend 20 mins next collab session looking at this, I think it could be easy to resolve (as in, we can make a decision once we have all info) but I don't have time right now

**Comment by laurianvm** [comment]
no need for that,
[internal github page](https://vliz.atlassian.net/wiki/spaces/VMDCOS/pages/93783049/EMO+BON+RO-Crates) indicates that dct:creator can be _:EMOBON 

so this is added to FE-DCATAP-metadata.json 
in extra-metadata.json, 'provider' remains as is
